version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Set reviewers for pull requests
    reviewers:
      - "Wiley-Consolidated-School/developers"
    # Allow up to 10 open pull requests at a time
    open-pull-requests-limit: 10
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automated"
    # Ignore certain major version updates to avoid breaking changes
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "Microsoft.Data.SqlClient"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
