name: Create Release

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: List repository contents
        run: |
          dir
          if (Test-Path "BusBuddy.sln") { Write-Host "Solution file found in root" } else { Write-Host "Solution file not found in root" }

      - name: Find solution file
        run: |
          Get-ChildItem -Path . -Filter *.sln -Recurse

      - name: Restore dependencies
        run: |
          $solutionPath = (Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1).FullName
          Write-Host "Found solution at $solutionPath"
          dotnet restore $solutionPath

      - name: Build
        run: |
          $solutionPath = (Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1).FullName
          dotnet build $solutionPath --no-restore --configuration Release

      - name: Publish Application
        run: |
          $solutionPath = (Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1).FullName
          dotnet publish $solutionPath -c Release --no-build -o publish

      - name: Create Zip Archive
        run: Compress-Archive -Path publish\* -DestinationPath BusBuddy.zip
        shell: pwsh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: BusBuddy.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
