name: Create Release

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore dependencies
        run: dotnet restore BusBuddy.sln
      
      - name: Build
        run: dotnet build BusBuddy.sln --no-restore --configuration Release
      
      - name: Publish Application
        run: dotnet publish BusBuddy.sln -c Release --no-build -o publish
      
      - name: Create Zip Archive
        run: Compress-Archive -Path publish\* -DestinationPath BusBuddy.zip
        shell: pwsh
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: BusBuddy.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
