name: Testing Standards Enforcement

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-standards:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Check code formatting
      run: dotnet format BusBuddy.sln --verify-no-changes --verbosity minimal

    - name: Run tests with coverage
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed"

    - name: Verify test naming conventions
      shell: pwsh
      run: |
        $testFiles = Get-ChildItem -Path "BusBuddy.UI.Tests" -Filter "*.cs" -Recurse
        $badNames = @()

        foreach ($file in $testFiles) {
          $content = Get-Content $file.FullName -Raw
          if ($content -match "public void (Test|test)\d+|public void [a-z]") {
            $badNames += $file.Name
          }
        }

        if ($badNames.Count -gt 0) {
          Write-Host "❌ Found test files with poor naming conventions:" -ForegroundColor Red
          $badNames | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
          Write-Host "Please use pattern: MethodName_Scenario_ExpectedBehavior" -ForegroundColor Yellow
          exit 1
        }

        Write-Host "✅ All test naming conventions are correct" -ForegroundColor Green

    - name: Check UI test threading
      shell: pwsh
      run: |
        $uiTestFiles = Get-ChildItem -Path "BusBuddy.UI.Tests" -Filter "*UI*.cs"
        $missingSTAThread = @()

        foreach ($file in $uiTestFiles) {
          $content = Get-Content $file.FullName -Raw
          if ($content -notmatch "\[STAThread\]") {
            $missingSTAThread += $file.Name
          }
        }

        if ($missingSTAThread.Count -gt 0) {
          Write-Host "⚠️ UI test files missing [STAThread] attribute:" -ForegroundColor Yellow
          $missingSTAThread | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
        } else {
          Write-Host "✅ All UI tests have proper threading attributes" -ForegroundColor Green
        }

    - name: Enforce xUnit-only tests
      shell: pwsh
      run: |
        Write-Host "Checking for non-xUnit test frameworks..." -ForegroundColor Cyan

        # Check for MSTest references
        $msTestFiles = @()
        $nunitFiles = @()
        $allProjects = Get-ChildItem -Path . -Filter "*.csproj" -Recurse

        foreach ($project in $allProjects) {
          $content = Get-Content $project.FullName -Raw
          if ($content -match "MSTest|Microsoft\.VisualStudio\.TestPlatform|TestMethod|Microsoft\.VisualStudio\.TestTools\.UnitTesting") {
            $msTestFiles += $project.FullName
          }
          if ($content -match "NUnit|nunit") {
            $nunitFiles += $project.FullName
          }
        }

        # Check for test files outside BusBuddy.UI.Tests
        $outsideTestFiles = @()
        $csharpFiles = Get-ChildItem -Path . -Filter "*.cs" -Recurse -Exclude "BusBuddy.UI.Tests\*"

        foreach ($file in $csharpFiles) {
          $content = Get-Content $file.FullName -Raw
          if ($content -match "\[Fact\]|\[Theory\]|\[Test\]|\[TestMethod\]|\[TestCase\]|\[TestFixture\]") {
            $outsideTestFiles += $file.FullName
          }
        }

        $hasErrors = $false

        if ($msTestFiles.Count -gt 0) {
          Write-Host "❌ Found MSTest references in projects:" -ForegroundColor Red
          $msTestFiles | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
          $hasErrors = $true
        }

        if ($nunitFiles.Count -gt 0) {
          Write-Host "❌ Found NUnit references in projects:" -ForegroundColor Red
          $nunitFiles | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
          $hasErrors = $true
        }

        if ($outsideTestFiles.Count -gt 0) {
          Write-Host "❌ Found test files outside BusBuddy.UI.Tests:" -ForegroundColor Red
          $outsideTestFiles | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
          $hasErrors = $true
        }

        if ($hasErrors) {
          Write-Host "Testing standards violation: Only xUnit tests in BusBuddy.UI.Tests are allowed." -ForegroundColor Red
          exit 1
        } else {
          Write-Host "✅ All tests use xUnit and are in the correct location" -ForegroundColor Green
        }

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./TestResults/*/coverage.cobertura.xml
        fail_ci_if_error: false

    - name: Test Summary
      if: always()
      run: |
        echo "## Testing Standards Report" >> $GITHUB_STEP_SUMMARY
        echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Build | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| Tests | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| Formatting | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| Naming Conventions | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| xUnit-only | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| Test Location | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
